---
title: "Getting started with Testcontainers in a Java SpringBoot Project"
date: 2023-02-14T09:39:58+05:30
draft: false
description: This guide will explain how to test SpringBoot and Spring Data JPA based REST APIs using Testcontainers.
repo: https://github.com/testcontainers/tc-guide-testing-spring-boot-rest-api
---
:codebase: https://raw.githubusercontent.com/testcontainers/tc-guide-testing-spring-boot-rest-api/main

In this guide you will learn how to

* Create a SpringBoot application
* Implement a REST API endpoint using Spring MVC, Spring Data Jpa and Postgres
* Test REST API using Testcontainers and RestAssured.

== Prerequisites
* Java 17+
* Your favorite IDE(Intellij IDEA, Eclipse, NetBeans, VS Code)
* Testcontainers supporting Docker environment https://www.testcontainers.org/supported_docker_environment/

== What we are going to achieve in this guide
We are going to create a SpringBoot project using Spring Data JPA, Postgres and
implement a REST API endpoint to return all the customer details.
Then we will test the API using Testcontainers postgres module and RestAssured.

== Getting Started
You can create a new SpringBoot project from Spring Initializr by selecting Spring Web,
Spring Data JPA, PostgreSQL Driver and Testcontainers starters.

Or you can clone https://github.com/testcontainers/tc-guide-spring-boot-rest-api-testing-guide.git repository
and switch to the initial branch.

We are going to test API using RestAssured, so let us add the rest-assured library dependency:
[source,xml]
----
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <scope>test</scope>
</dependency>
----

If you have selected the Maven build tool you can see the following SpringBoot starters and
Testcontainers postgres module dependencies are added to pom.xml.

[source,groovy]
----
include::{codebase}/pom.xml[lines="18..68"]
----

If you have selected the Gradle build tool then build.gradle is configured with selected dependencies.

[source,groovy]
----
include::{codebase}/build.gradle[lines="20..40"]
----

Using Testcontainers BOM (Bill Of Material) is highly recommended so that you don't have to repeat
testcontainers version while using multiple Testcontainers modules.

== Create JPA entity
First let us start with creating a JPA entity *Customer.java*.

[source,java]
----
include::{codebase}/src/main/java/com/testcontainers/demo/Customer.java[]
----

== Create Spring Data JPA Repository
Spring Data JPA is an abstraction on top of JPA by providing basic CRUD operations,
sorting and pagination capabilities and dynamic query generation from method names.

Let us create a Spring Data Jpa repository interface for the Customer entity.

[source,java]
----
include::{codebase}/src/main/java/com/testcontainers/demo/CustomerRepository.java[]
----

== Add Schema Creation Script
As we are not using any in-memory database, we need to create postgres database tables by some means.
The recommended approach is to use some database migration tool like Flyway or Liquibase,
but for this guide we will use simple schema initialization support provided by SpringBoot.

Create schema.sql file with following SQL script under src/main/resources directory.

[source,sql]
----
include::{codebase}/src/main/resources/schema.sql[]
----

We need to enable schema initialization by adding the following property in src/main/resources/application.properties file.

[source,properties]
----
spring.sql.init.mode=always
----

== Create REST API endpoint
Create a controller to implement a REST API endpoint to get all customers.

[source,java]
----
include::{codebase}/src/main/java/com/testcontainers/demo/CustomerController.java[]
----

== Write Test for API endpoint
We are going to write a test for REST API GET /api/customers endpoint by starting the SpringBoot application
using @SpringBootTest annotation and invoke APIs using RestAssured.

But in order to start our SpringBoot application we need a Postgres database up and running and
configure the application to talk to that database. This is where Testcontainers comes into the picture.

We can use the Testcontainers library to spin up a Postgres database instance as a docker container and
configure the application to talk to that database as follows:

[source,java]
----
include::{codebase}/src/test/java/com/testcontainers/demo/CustomerControllerTest.java[]
----

Let us understand what is going on in this test.

* We have annotated the test class with *@SpringBootTest* annotation so that the test will run by starting the entire application on a random available port.
* We have created an instance of *PostgreSQLContainer* with *postgres:15-alpine* docker image. The postgres container is started using JUnit 5 *@BeforeAll* callback method which gets executed before running any test methods.
* The Postgres database runs on port 5432 inside the container and maps to a random available port on the Host.
* We have registered the database connection properties obtained from the Postgres container using SpringBoot's *DynamicPropertyRegistry*.
* We have captured the random port on which the SpringBoot application started using *@LocalServerPort* and registered the *RestAssured* baseURI.
* We are deleting customer rows if there exists any using JUnit 5 *@BeforeEach* callback method which gets executed before every test method. This will ensure the predictable data setup for every test.
* Finally, in the *shouldGetAllCustomers()* test, we have initialized the test data and invoked *GET /api/customers* API endpoint and verified that 2 customer records are returned from the API.

== Run Test

[source,shell]
----
# If you are using Maven
./mvnw test

# If you are using Gradle
./gradlew test
----

You should see the Postgres docker container is started and all tests should PASS.
You can also notice that after tests are executed the containers are stopped and removed automatically.

== Summary
Testcontainers library helped us to write integration tests by using the same type of database, postgres,
that we use in production as opposed to mocks or in-memory databases.
As we are not using mocks and talking to the real services, we are free to do any code refactoring and
still ensure that the application is working as expected.

To learn more about Testcontainers visit http://testcontainers.com

== Further Reading
* https://www.testcontainers.org/quickstart/junit_5_quickstart/
* https://www.testcontainers.org/modules/databases/postgres/
* https://www.testcontainers.org/modules/databases/jdbc/
* https://spring.io/blog/2020/03/27/dynamicpropertysource-in-spring-framework-5-2-5-and-spring-boot-2-2-6
